### ISSUE TITLE
Error encounter when executing quote_server command line in local environment

### ISSUE THREAD

**Issue by zhlsunshine** [intel/confidential-cloud-native-primitives#106]
There is the step list to reproduce the error:
1. build the quote_server via `make build` in `confidential-cloud-native-primitives/service/quote-server`
2. execute the `quote_server` command in `confidential-cloud-native-primitives/service/quote-server/target/release`
3. the error show below:

```
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
I located the code [here](https://github.com/intel/confidential-cloud-native-primitives/blob/4a77d7f6a4049481a0af8fba94c306ed2060fd93/service/quote-server/src/quote_server.rs#L70), IMO, there should be some other necessary codes to fix it, otherwise the error will occur once there is no socket file `/run/ccnp/uds/quote-server.sock`

**Comment by hairongchen** [comment]
Hi @zhlsunshine thanks for raise this up, can you pls try change the permission of dir /run/ccnp/uds/ to add write permission to this directory for other users per step2 of  [Introduction] (https://github.com/intel/confidential-cloud-native-primitives/tree/main/device-plugin/ccnp-device-plugin#prerequisite) and try again?

**Comment by zhlsunshine** [comment]
> Hi @zhlsunshine thanks for raise this up, can you pls try change the permission of dir /run/ccnp/uds/ to add write permission to this directory for other users per step2 of [Introduction] (https://github.com/intel/confidential-cloud-native-primitives/tree/main/device-plugin/ccnp-device-plugin#prerequisite) and try again?

Hi @hairongchen, in fact there is no `/run/ccnp/uds/` folder in my local environment, as you know I execute this binary in command line. I believe this dir is created when you deploy quote_service as a daemonset by yaml. such as something mount volume in advance.

**Comment by hairongchen** [comment]
That's correct. And this directory is actually shared by other two servers(measurement and eventlog), we don't want a single server to take the control of this shared directory, to run quote server in straight binary, one can create the directory yourself, and I'll update the readme to include this tip.

And for CCNP usage, we'll have a task added in TDVM startup to make sure if using CCNP with TDVM image built from tdx-tools, this dir will be created and correctly permissioned.

**Comment by zhlsunshine** [comment]
okay, thanks for your explains for this part, and thank you for adding tips for this issue.

**Comment by hairongchen** [comment]
see also: https://github.com/intel/tdx-tools/pull/479
