### ISSUE TITLE
CCNP quote SDK return result enhancement to provided clear usage to client

### ISSUE THREAD

**Issue by hairongchen** [intel/confidential-cloud-native-primitives#137]
### What would you like to be added?

Now quote SDK has python and golang implementation for TDX, there are several issues need to be considered depends on how client would use the SDK return results and what if more TEEs are added:

- how the client would know the return is a specific TEE related quote information
- one comment fields for all the TEEs is quote, but if client want to access specific fields in TEE quote, how the fields should be stored in the result or we can simply provide a tool function to let client call the tool with quote to get the fields
- sync the naming of all the fields for a TEE in different language SDKs and make a simple and clear documentation for end user
- does not break client's current usage model
- the return should container raw data like TEE report or TEE quote, and the raw data should be base64 encoded or simply raw binary string 

### Why is this needed?

End user should have a simple and clear understanding on SDK returns.

**Comment by Ruoyu-y** [comment]
Current thoughts: The common property that is clearly defined for now is the raw 'quote'. Most attributes in the quote are different in different hardware environments. If it is not possible to extract common attributes or structure, Is it possible to define a struct like this:
```
type QuoteInfo struct {
rawQuote []uint8
parsedQuote map[string]uint8
}
```
User can find the quote details by checking the map.

**Comment by hairongchen** [comment]
**Solution Option 1**
![image](https://github.com/intel/confidential-cloud-native-primitives/assets/105473940/9b2272b8-017d-4d50-9031-14db1b0624d8)
![image](https://github.com/intel/confidential-cloud-native-primitives/assets/105473940/d1dca9fa-b497-4228-a89c-edc8ab9e6783)

**Solution Option 2**
![image](https://github.com/intel/confidential-cloud-native-primitives/assets/105473940/aa3239db-0566-48e5-8d23-ee1acc6faff1)
![image](https://github.com/intel/confidential-cloud-native-primitives/assets/105473940/328472f0-a073-48f7-a2f4-4760c0592a06)

**Comment by hairongchen** [comment]
f
