### ISSUE TITLE
Exploration for SDK generator feasibility.

### ISSUE THREAD

**Issue by jiere** [intel/confidential-cloud-native-primitives#144]
### What would you like to be added?

I found this client SDK dev [methodology](https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/dev/src/clients) by accident, which leverages the `openapi-generator` CLI to generate programming language specific SDK code.

What I am thinking is that if we CCNP has feasibility to define CC APIs as RESTful as Open API, so that we just need to maintain those swagger.json files and let the SDK code skeleton be generated automatically.

### Why is this needed?

Focus more on the API definition, fully leverage the generator techniques for SDK code skeleton and documents.

Focus more on specific SDK routines implementation.

**Comment by kenplusplus** [comment]
Let move this to discussions https://github.com/intel/confidential-cloud-native-primitives/discussions/219
